version: '3'

services:
  backend:
    build: ./fastapi-backend
    ports:
      - "8000:8000"

  frontend:
    build: ./my-app     # Adjust this to match the folder name for React
    ports:
      - "3000:3000"
