name: Deploy to VM and ACR

on:
  push:
    branches:
      - main  # Trigger the action on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Check out the repository code

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: qhinhprd.azurecr.io  # Your ACR login server
        username: ${{ secrets.ACR_USERNAME }}  # Username from GitHub Secrets
        password: ${{ secrets.ACR_PASSWORD }}  # Password from GitHub Secrets

    - name: Build and push backend image
      run: |
        docker build -t qhinhprd.azurecr.io/fastapi-backend:latest ./fastapi-backend
        docker push qhinhprd.azurecr.io/fastapi-backend:latest
        
    - name: Build and push frontend image
      run: |
        docker build -t qhinhprd.azurecr.io/my-app:latest ./my-app
        docker push qhinhprd.azurecr.io/my-app:latest
        
    - name: Run SonarQube Analysis
      run: |
        docker run --rm \
          -e SONAR_HOST_URL="http://74.225.172.238:9000" \
          -e SONAR_LOGIN="sqp_651f083982e693c269499b4cc8eeacb4024fb529" \
          -v "$(pwd):/usr/src" \
          sonarsource/sonar-scanner-cli:latest \
          -Dsonar.projectKey=github-project \
          -Dsonar.projectName=github-project \
          -Dsonar.sources=/usr/src \
          -Dsonar.host.url=http://74.225.172.238:9000 \
          -Dsonar.login="sqp_651f083982e693c269499b4cc8eeacb4024fb529"

    - name: Deploy to VM
      uses: appleboy/ssh-action@v0.1.6  # Use appleboy SSH action
      with:
        host: ${{ secrets.VM_IP }}  # VM IP address from GitHub Secrets
        username: ${{ secrets.VM_USER }}  # VM user from GitHub Secrets
        key: ${{ secrets.SSH_PRIVATE_KEY }}  # Private SSH key from GitHub Secrets
        passphrase: "qh-adm"  # Passphrase from GitHub Secrets
        script: |
          # Log in to Azure Container Registry on the VM
          #az acr login --name qhinhprd --username ${{ secrets.ACR_USERNAME }} --password ${{ secrets.ACR_PASSWORD }}
          
          # Pull and run backend Docker container
          docker pull qhinhprd.azurecr.io/fastapi-backend:latest
          docker run -d -p 5000:8000 qhinhprd.azurecr.io/fastapi-backend:latest
          
          # Pull and run frontend Docker container
          docker pull qhinhprd.azurecr.io/my-app:latest
          docker run -d -p 6000:3000 qhinhprd.azurecr.io/my-app:latest
