name: Build and Push to ACR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: qhinhprd.azurecr.io
          username: qhinhprd
         

      - name: Build and push Frontend image
        run: |
          docker build -t qhinhprd.azurecr.io/frontend:latest ./my-app
          docker push qhinhprd.azurecr.io/frontend:latest

      - name: Build and push Backend image
        run: |
          docker build -t qhinhprd.azurecr.io/backend:latest ./fastapi-backend
          docker push qhinhprd.azurecr.io/backend:latest
